### ISSUE TITLE
Datasets missing key 'rationale_labels'

### ISSUE THREAD

**Issue by tarushbansal** [behavioral-data/Empathy-Mental-Health#15]
I encounter the following error trace while running the train scripts as per the instructions:

Traceback (most recent call last):
  File "src/train.py", line 77, in <module>
    df['rationale_labels'] = df['rationale_labels'].apply(lambda s: torch.tensor(np.asarray([int(i) for i in s.split(',')]), dtype=torch.long))
  File "/home/tb662/env/project/lib/python3.8/site-packages/pandas/core/frame.py", line 3807, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/tb662/env/project/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3804, in get_loc
    raise KeyError(key) from err
KeyError: 'rationale_labels'

I think the data might be missing the 'rationale_labels' column. Will be helpful if this could be fixed because currently I cannot train new models.

**Comment by syedwaleedhyder** [comment]
Have you done the following step? 
https://github.com/behavioral-data/Empathy-Mental-Health/tree/396f6e0e3250c695a7a529fd1e2c86d2adffdc41#2-prepare-dataset
